name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://52.68.233.193:10021/api/v1/ci-start'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: >-
            {
              "env": "prod",
              "repo": "git@github.com:shadouzuo/executor-task.git",
              "fetch_code_key": "~/.ssh/github_pefish",
              "port": 0,
              "alert_tg_token": "6886244250:AAE7za4HAuXPPoCvi-5AYseQP2FjCD591QA",
              "alert_tg_group_id": "-4165544291",
              "docker_network": "jinniu"
            }

